// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxi5tfDUNbSrdMWfdaC1j84DTfTJBGbEc',
    appId: '1:377919689277:web:69f6a06e6367e567f75054',
    messagingSenderId: '377919689277',
    projectId: 'shoq-bfa54',
    authDomain: 'shoq-bfa54.firebaseapp.com',
    storageBucket: 'shoq-bfa54.firebasestorage.app',
    measurementId: 'G-8CMMYFG1NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW-MIvjpgegCfrlOuDWpmuT5lF0iRHPgg',
    appId: '1:377919689277:android:004ab00751723f6ef75054',
    messagingSenderId: '377919689277',
    projectId: 'shoq-bfa54',
    storageBucket: 'shoq-bfa54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCar00STVscr5GJbT4Gz4NJqJInvDU9b1I',
    appId: '1:377919689277:ios:493fb401cfdca579f75054',
    messagingSenderId: '377919689277',
    projectId: 'shoq-bfa54',
    storageBucket: 'shoq-bfa54.firebasestorage.app',
    iosClientId: '377919689277-0co4v7267bl27dg5i4vtbr5k782iq9lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCar00STVscr5GJbT4Gz4NJqJInvDU9b1I',
    appId: '1:377919689277:ios:493fb401cfdca579f75054',
    messagingSenderId: '377919689277',
    projectId: 'shoq-bfa54',
    storageBucket: 'shoq-bfa54.firebasestorage.app',
    iosClientId: '377919689277-0co4v7267bl27dg5i4vtbr5k782iq9lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxi5tfDUNbSrdMWfdaC1j84DTfTJBGbEc',
    appId: '1:377919689277:web:6ad4f2a3edee5f58f75054',
    messagingSenderId: '377919689277',
    projectId: 'shoq-bfa54',
    authDomain: 'shoq-bfa54.firebaseapp.com',
    storageBucket: 'shoq-bfa54.firebasestorage.app',
    measurementId: 'G-H20V67L4ET',
  );
}
