# iOS platform version
platform :ios, '13.0'

# CocoaPods target for the Flutter Runner app
target 'Runner' do
  use_frameworks!
  use_modular_headers!

  
  # Force compatible pod versions to fix Firebase + MLKit conflicts
  pod 'Firebase/CoreOnly', '11.15.0'
  pod 'FirebaseCore', '11.15.0'
  pod 'FirebaseAuth', '11.15.0'
  pod 'FirebaseMessaging', '11.15.0'
  pod 'CloudFirestore', '11.15.0'
  pod 'GoogleUtilities', '8.1.0'
  pod 'GoogleMLKit/MLKitCore', '6.0.0'
  pod 'GoogleMLKit/BarcodeScanning', '6.0.0'
end

# Post-install hook for Flutter build settings
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
